# Generated by Django 5.0.6 on 2024-08-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_min', models.FloatField()),
                ('wwl', models.FloatField()),
                ('lwl', models.FloatField()),
                ('wvpi', models.FloatField()),
                ('ukc', models.FloatField()),
                ('dx_min', models.FloatField()),
                ('blend', models.FloatField()),
                ('nl_c', models.FloatField()),
                ('nl_m', models.FloatField()),
            ],
        ),
    ]
