# Generated by Django 5.0.6 on 2024-08-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersubmission',
            name='start',
            field=models.CharField(default='64,28', max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='blend',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='dx_min',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='lwl',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='nl_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='nl_m',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='ukc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='wd_min',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='wvpi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parametersubmission',
            name='wwl',
            field=models.CharField(max_length=255),
        ),
    ]
