# Generated by Django 5.0.6 on 2024-08-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipdata', '0002_parametersubmission_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersubmission',
            name='start',
            field=models.CharField(max_length=255),
        ),
    ]
