# Generated by Django 5.0.6 on 2024-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipdata', '0003_alter_parametersubmission_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersubmission',
            name='stop',
            field=models.CharField(default='51,11', max_length=255),
        ),
    ]
